# This is a configuration file for simulation.
# The file will be passed to an instance of Simulator() in which
# an optimization problem is solved according to this configuration.

# Tutorial for your project:
# 1. Update the 'project_name' variable to match the actual name of your project.
# 2. Customize the 'problem_initialpoint', 'problem_coordinator_name', and 'solver_name' to match your specific experiments.
#    Make sure that 'problem_coordinator_name' corresponds to the file name of your ProblemCoordinator subclass in the project.
# 3. Edit the 'solver_option'. 'solver_option-common' contains shared settings for all solvers,
#    while 'solver_option-{solver_name}' contains specific settings for each individual solver you are using.
# 4. If you plan to use multi-run functionality in the simulation, modify 'hydra-sweeper-params' to set the appropriate multi-run range.
#     This allows you to conduct simulations with various configurations efficiently.
#
# Next, please proceed to the 'simulator.py'.

problem_name: 'Model_Ob'
problem_instance: 1  # can be swept by multi-run
problem_initialpoint: a  # can be swept by multi-run
problem_coordinator_name: "coordinator"  # called in simulator to set a problem
solver_name: ["RALM", "RSQO"]

solver_option:
    # Common settings: stopping criteria and wandb setting
    common:
      maxtime: 100  # max time of experiments as a stopping criterion
      maxiter: 100  # max iteration as a stopping criterion
      tolresid: 1e-12  # tolerance of residual based on KKT conditions as a stopping criterion
      verbosity: 1
      wandb_logging: False  # Set True for sending the experimental results to wandb
      wandb_project: ${problem_name}-${problem_instance}-${problem_initialpoint}  # project name in wandb
    # Settings specific to each solver
    RALM:
      rho: 0.1
### NOTE ###
# Experimental results are stored in 'intermediate/${problem_name}/${problem_instance}/${problem_initialpoint}'.

# Sweep settings.
output_path: intermediate/${problem_name}/${problem_instance}/${problem_initialpoint}
hydra:
  run:
    dir: intermediate/${problem_name}
  sweeper:
    params:
      problem_instance: 1,2,3
      problem_initialpoint: a,b,c
      solver_name: ["RALM"]