# This is a configuration file for simulation.
# The file will be passed to an instance of Simulator() in which
# an optimization problem is solved according to this configuration.

problem_name: 'PackingCircles'
problem_instance: 1  # can be swept by multi-run
problem_initialpoint: a  # can be swept by multi-run
problem_coordinator_name: "euclidean_coordinator"  # called in simulator to set a problem
solver_name: ["EuclideanIPTRM"]

solver_option:
    # Common settings: stopping criteria and wandb setting
    common:
      maxtime: 100  # max time of experiments as a stopping criterion
      maxiter: 1000  # max iteration as a stopping criterion
      tolresid: 0  # tolerance of residual based on KKT conditions as a stopping criterion
      verbosity: 2
      wandb_logging: True  # Set True for sending the experimental results to wandb
      wandb_project: ${problem_name}-${problem_instance}-${problem_initialpoint}  # project name in wandb
    # Settings specific to each solver

### NOTE ###
# Experimental results are stored in 'intermediate/${problem_name}/${problem_instance}/${problem_initialpoint}'.

# Sweep settings.
output_path: intermediate/${problem_name}/${problem_instance}/${problem_initialpoint}
hydra:
  run:
    dir: intermediate/${problem_name}
  sweeper:
    params:
      problem_instance: 1,2,3
      problem_initialpoint: a,b,c
      solver_name: ["EuclideanIPTRM"]