# This is a configuration file for simulation in nonnegative principal component analysis.
# The file will be passed to an instance of Simulator() in which
# an optimization problem is solved according to this configuration.

problem_name: 'NonnegPCA'
problem_instance: 3  # can be swept by multi-run
problem_initialpoint: a  # can be swept by multi-run
problem_coordinator_name: "coordinator"  # called in simulator to set a problem
solver_name: ["RSQO", "RALM"]

solver_option:
    # Common settings: stopping criteria and wandb setting
    common:
      maxtime: 3600  # max time of experiments as a stopping criterion
      maxiter: 100  # max iteration as a stopping criterion
      tolresid: 1e-10  # tolerance of residual based on KKT conditions as a stopping criterion
      wandb_logging: True  # Set True for sending the experimental results to wandb
      wandb_project: ${problem_name}-${problem_instance}-${problem_initialpoint}  # project name in wandb
      verbosity: 1  # verbosity of solver
    # Settings specific to each solver
    RALM:
      rho: 0.1
### NOTE ###
# Experimental results are stored in 'intermediate/${problem_name}/${problem_instance}/${problem_initialpoint}'.

# Sweep settings.
output_path: intermediate/${problem_name}/${problem_instance}/${problem_initialpoint}
hydra:
  run:
    dir: intermediate/${problem_name}
  sweeper:
    params:
      problem_instance: 1,2,3
      problem_initialpoint: a,b,c
      solver_name: ["RALM"]